### ISSUE TITLE
Course 2 Week 3 - Only passed with 80%

### ISSUE THREAD

**Issue by trungnt2910** [D-ENCODER/GOOGLE-IT-AUTOMATION#2]
After attempting to do the Qwiklabs assignment myself and only got an 80% mark on Coursera, I found [this file](https://github.com/D-ENCODER/GOOGLE-IT-AUTOMATION/blob/master/Using%20Python%20to%20Interact%20with%20the%20Operating%20System/Week-3/script.py) on your repo. However, submitting that still only got me an 80% mark.

What's wrong here?

**Comment by D-ENCODER** [comment]
hey @trungnt2910 nice to have you here can you please send some more information on the errors or some screenshots of the same. It will be more helpful

**Comment by D-ENCODER** [comment]
and do change this [part of the code](https://github.com/D-ENCODER/GOOGLE-IT-AUTOMATION/blob/master/Using%20Python%20to%20Interact%20with%20the%20Operating%20System/Week-3/script.py#L22-L23) to your actual credentials and un-comment them before submitting

**Comment by trungnt2910** [comment]
> and do change this [part of the code](https://github.com/D-ENCODER/GOOGLE-IT-AUTOMATION/blob/master/Using%20Python%20to%20Interact%20with%20the%20Operating%20System/Week-3/script.py#L22-L23) to your actual credentials and un-comment them before submitting

Yes, I am aware. I did do that.

> hey @trungnt2910 nice to have you here can you please send some more information on the errors or some screenshots of the same. It will be more helpful

There weren't any errors on Qwiklabs, I completed the task successfully, received 5/5 marks, and then ended the lab.
But back on my Coursera page, I got this:
![image](https://user-images.githubusercontent.com/57174311/192191405-18d4766b-598d-4ade-8504-900115d96a5c.png)

Qwiklabs didn't report any error but I only got an 80% mark for the task.

**Comment by trungnt2910** [comment]
This is a misunderstanding on my side. "Passed 80%" means that the minimum passing grade is 80%, and not the actual grade the user scored on the exercise.

**Comment by D-ENCODER** [comment]
i am glad that this repository helped you, do spend a moment to star this repository.
peace out 🤞
